/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import java.lang.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import app.Conversion;

public class ConversionTest {
    
    @Test public void toMillimetersTest1() {
        System.out.println("Conversao de metros inteiros para milimetros");
        Integer a = new Integer (-21);
        Conversion conTest = new Conversion();
        Integer resultado1 = conTest.toMillimeters(a);
        assertEquals(null, resultado1); //Compara se os dois resultados são iguais
        
    }
    @Test public void toMillimetersTest2() {
        System.out.println("Conversao de metros inteiros para milimetros");
        Integer b = new Integer (13000000);
        Conversion conTest = new Conversion();
        Integer resultado2 = conTest.toMillimeters(b);
        assertEquals(null, resultado2); //Compara se os dois resultados são iguais
        
    }
    @Test public void toMillimetersTest3() {
        System.out.println("Conversao de metros inteiros para milimetros");
        Integer c = new Integer (7);
        Conversion conTest = new Conversion();
        Integer resultado3 = conTest.toMillimeters(c);
        Integer esperado = new Integer (7100);
        assertEquals(esperado, resultado3); //Compara se os dois resultados são iguais
        
    }
}
