/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;
import java.lang.*;


public class App {
    public String getGreeting() {
        return "Entrega 1";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Conversion con = new Conversion();
        Integer result = con.toMillimeters(2);
        Integer result2 = con.toMillimeters(7);
        System.out.println("Conversao de metros inteiros para milimetros\n");
        System.out.println("Valor inteiro em metros: 2");
        System.out.printf("Valor inteiro em milimetros: %d\n\n", result);
        System.out.println("Valor inteiro em metros: 7");
        System.out.printf("Valor inteiro em milimetros: %d", result2);
    }
}
