/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;
//import src\main\java\app\Conversion.java;

public class App {
    public String getGreeting() {
        return "Entrega 1";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Conversion con = new Conversion();
        con.toMillimeters(2);
    }
}
