/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import java.lang.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import app.Conversion;

public class ConversionTest {
    
    @Test public void toMillimetersTest1() {
        System.out.println("Conversao de metros inteiros para milimetros");
        Integer a = 2;
        Conversion conTest = new Conversion();
        Integer resultado1 = conTest.toMillimeters(a);
        Integer esperado1 = 2000;
        assertEquals(esperado1, resultado1); //Compara se os dois resultados são iguais
        
    }
    @Test public void toMillimetersTest2() {
        System.out.println("Conversao de metros inteiros para milimetros");
        Integer b = 5;
        Conversion conTest = new Conversion();
        Integer resultado2 = conTest.toMillimeters(b);
        Integer esperado2 = 5000;
        assertEquals(esperado2, resultado2); //Compara se os dois resultados são iguais
        
    }
    
}
